---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ratelimit.itbl.sre.co
  resources:
  - ratelimitedconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.itbl.sre.co
  resources:
  - ratelimitedconsumers/finalizers
  verbs:
  - update
- apiGroups:
  - ratelimit.itbl.sre.co
  resources:
  - ratelimitedconsumers/status
  verbs:
  - get
  - patch
  - update
