apiVersion: ratelimit.test.annotation.com/v1alpha1
kind: RateLimitedConsumer
metadata:
  labels:
    app.kubernetes.io/name: k8s-simple-controller
    app.kubernetes.io/managed-by: kustomize
  name: ratelimitedconsumer-sample
spec:
  rateLimit:
    names: 
      - test-rate-limit
  targetRoute:
    name: dummy-route
